[
    {
        "id": "f367b286.aeeee",
        "type": "tab",
        "label": "Catch Error",
        "disabled": false,
        "info": ""
    },
    {
        "id": "d93a3975.aaece8",
        "type": "inject",
        "z": "f367b286.aeeee",
        "name": "",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Hello, World!",
        "payloadType": "str",
        "x": 210,
        "y": 240,
        "wires": [
            [
                "1c96104f.ea8d5"
            ]
        ]
    },
    {
        "id": "d1bedbf7.f4cb58",
        "type": "debug",
        "z": "f367b286.aeeee",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 530,
        "y": 280,
        "wires": []
    },
    {
        "id": "f3918c41.eb3ea",
        "type": "comment",
        "z": "f367b286.aeeee",
        "name": "Catch",
        "info": "Com o nó `Catch`, conseguimos capturar erros provenientes de outros nós. Em sua configuração, é possível selecionar nós específicos ou simplesmente não selecionar, o que permitirá que o nó `Catch` capture qualquer erro de qualquer nó.\n\nÉ como se esse nó ficasse \"ouvindo\" o que está a sua volta e acionado quando \"percebesse\" alguma falha. A partir daí, podemos ter detalhes da falha, como por exemplo: mensagem de erro, momento em que ocorreu, qual o nó que emitiu, etc.. Além de nos possibilitar tomar quaisquer medidas necessárias.\n\nNeste exemplo, estamos simulando um erro em um dos nós. Com a tela lateral de debug ativada, clique no botão do nó `Inject` e leia o documento que o nó `Catch` gerou.",
        "x": 130,
        "y": 160,
        "wires": []
    },
    {
        "id": "3c7ce791.cc5798",
        "type": "catch",
        "z": "f367b286.aeeee",
        "name": "",
        "scope": [
            "1c96104f.ea8d5"
        ],
        "uncaught": false,
        "x": 380,
        "y": 280,
        "wires": [
            [
                "d1bedbf7.f4cb58"
            ]
        ]
    },
    {
        "id": "1c96104f.ea8d5",
        "type": "function",
        "z": "f367b286.aeeee",
        "name": "Error",
        "func": "throw new Error(\"Error Occured!\")",
        "outputs": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "x": 370,
        "y": 240,
        "wires": []
    }
]